#For the data format, please refer to https://docs.ultralytics.com/datasets/segment/coco/

# dataset root directory
path: /home/research/Desktop/brats/yolo/YOLO11-seg/dataset

# train images relative ('relative to path')
train: images/train
val: images/val
test: images/test

# Classes
nc: 1
names: ["whole_tumor"]
